
#define SSBO_IDX_SAMPLERS       0
#define SSBO_IDX_RENDERER_DATA  1
#define SSBO_IDX_VIEWPORT_DATA  2
#define SSBO_IDX_INSTANCE_DATA  3
#define SSBO_IDX_LIGHTS         4

#define TEX_IDX_SHADOW_MAP_FLASHLIGHT 0
#define TEX_IDX_SHADOW_MAP_HI_RES     1
#define TEX_IDX_SHADOW_MAP_LOW_RES    2
#define TEX_IDX_SHADOW_MAP_CSM        3
