#version 460 core
#include "../common/types.glsl"

layout (local_size_x = 16, local_size_y = 4, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D outputImage;
layout(binding = 1) uniform sampler2D emissiveBlurTexture;

uniform int u_viewportIndex;

readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer {
    ViewportData viewportData[];
};

void main() {
    ivec2 offset = ivec2(viewportData[u_viewportIndex].xOffset, viewportData[u_viewportIndex].yOffset);
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy) + offset;   
    
    // Map pixel to global screen uv so we sample the correct splitscreen quadrant
    vec2 fullScreenSize = vec2(imageSize(outputImage));
    vec2 absolute_uv = vec2(pixelCoords) / fullScreenSize;

    vec4 finalColor = vec4(0.0);
    finalColor.a = 1.0;
    
    // Extract specific mips
    finalColor.rgb += textureLod(emissiveBlurTexture, absolute_uv, 0.0).rgb;
    finalColor.rgb += textureLod(emissiveBlurTexture, absolute_uv, 1.0).rgb;
    finalColor.rgb += textureLod(emissiveBlurTexture, absolute_uv, 2.0).rgb;
    finalColor.rgb += textureLod(emissiveBlurTexture, absolute_uv, 3.0).rgb;
    
    finalColor.rgb *= 0.6;
    finalColor += imageLoad(outputImage, pixelCoords);

    //finalColor.rgb = textureLod(emissiveBlurTexture, absolute_uv, 0.0).rgb;

    imageStore(outputImage, pixelCoords, finalColor);
}