#version 460 core
#include "../common/OpenGL/GL_binding_indices.glsl"
#include "../common/constants.glsl"
#include "../common/reconstruction.glsl"
#include "../common/util.glsl"
#include "../common/types.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D HeightMapTexture;
//layout(binding = 1) uniform sampler2D WorldPositionTexture;
layout(binding = 3) uniform sampler2D RoadMaskTexture;
layout(binding = 4) uniform sampler2D u_depthTexture;

uniform int gridSize;
uniform vec3 offset;
uniform float u_heightMapWorldSpaceSize;
uniform float spacing2;
uniform int u_viewportIndex;
uniform float u_waterHeight;

struct Vertex {
    float position[3];
    float normal[3];
};

layout(std430, binding = SSBO_IDX_GRASS_POSITION_INDIRECT_COMMAND) buffer IndirectDraw {
    uint count;
    uint instanceCount;
    uint firstVertex;
    int baseInstance;
} drawCmd;

readonly layout(std430, binding = SSBO_IDX_VIEWPORT_DATA) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };
layout(std430, binding = SSBO_IDX_GRASS_POSITION_INPUT_VERTICES) buffer inputVertexBuffer { Vertex InputVertexBuffer[]; };
layout(std430, binding = SSBO_IDX_GRASS_POSITION_INPUT_INDICES) buffer inputIndexBuffer { uint InputIndexBuffer[]; };
layout(std430, binding = SSBO_IDX_GRASS_POSITION_BLADE_POSITIONS) buffer BladePositions { vec4 bladePositions[]; };

float SignedDistance(vec3 point, vec4 plane) {
    return dot(plane.xyz, point) + plane.w;
}

bool IntersectsPoint(vec3 point, int viewportIndex) {
    vec4 frustumPlanes[6];
    frustumPlanes[0] = viewportDataArr[viewportIndex].frustumPlane0;
    frustumPlanes[1] = viewportDataArr[viewportIndex].frustumPlane1;
    frustumPlanes[2] = viewportDataArr[viewportIndex].frustumPlane2;
    frustumPlanes[3] = viewportDataArr[viewportIndex].frustumPlane3;
    frustumPlanes[4] = viewportDataArr[viewportIndex].frustumPlane4;
    frustumPlanes[5] = viewportDataArr[viewportIndex].frustumPlane5;

    for (int i = 0; i < 6; i++) {
        float distance = SignedDistance(point, frustumPlanes[i]);
        if (distance < 0) { // Fully outside
            return false;
        }
    }
    return true;
}

bool IntersectsSphere(vec3 center, float radius, int viewportIndex) {
    vec4 P0 = viewportDataArr[viewportIndex].frustumPlane0;
    vec4 P1 = viewportDataArr[viewportIndex].frustumPlane1;
    vec4 P2 = viewportDataArr[viewportIndex].frustumPlane2;
    vec4 P3 = viewportDataArr[viewportIndex].frustumPlane3;
    vec4 P4 = viewportDataArr[viewportIndex].frustumPlane4;
    vec4 P5 = viewportDataArr[viewportIndex].frustumPlane5;
    if (SignedDistance(center, P0) < -radius) return false;
    if (SignedDistance(center, P1) < -radius) return false;
    if (SignedDistance(center, P2) < -radius) return false;
    if (SignedDistance(center, P3) < -radius) return false;
    if (SignedDistance(center, P4) < -radius) return false;
    if (SignedDistance(center, P5) < -radius) return false;
    return true;
}

uint RandomUInt(vec2 seedVec, uint max) {
    // Hash the vec2 into a uint
    uint seed = floatBitsToUint(seedVec.x) ^ floatBitsToUint(seedVec.y);
    seed ^= 2747636419u;
    seed *= 2654435761u;
    seed ^= seed >> 16;
    seed *= 2654435761u;
    seed ^= seed >> 16;

    // Map the result to range [0, max]
    return seed % (max + 1u);
}

void main() {
    // tweakables
    float bendStrength = 0.1;
    float bladeHeight = 0.075;
    float bottomWidth = 0.005;
    float topWidth = 0.002;

    float spacing = 0.05;
    spacing = 0.0185185185185185;

    int viewportIndex = u_viewportIndex;

    //uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(gl_GlobalInvocationID.xy) + 0.5) / vec2(textureSize(u_depthTexture, 0));

    ViewportData viewportData = viewportDataArr[viewportIndex];
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportData);

    mat4 projectionView = viewportData.jitteredProjectionViewReverseZ;
    mat4 inverseProjectionView = viewportData.inverseJitteredProjectionViewReverseZ;
    mat4 inverseProjection = viewportData.inverseProjectionReverseZ;

    mat4 inverseView = viewportData.inverseView;
    vec3 viewPos = viewportData.viewPos.xyz;
    vec2 viewportSize = vec2(viewportData.sizeX, viewportData.sizeY);
    vec2 viewportPos = vec2(viewportData.posX, viewportData.posY);

    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    //int index = gid.y * gridSize + gid.x;

    // World position
    //float posX = float(gid.x) * spacing + floor(offset.x / spacing) * spacing;
    //float posZ = float(gid.y) * spacing + floor(offset.z / spacing) * spacing;

    float posX = float(gl_GlobalInvocationID.x) * spacing + offset.x;
    float posZ = float(gl_GlobalInvocationID.y) * spacing + offset.z;

    vec2 heightMapDimensions = textureSize(HeightMapTexture, 0) * HEIGHTMAP_SCALE_XZ;
    vec2 normalizedCoords = vec2(posX / heightMapDimensions.x, posZ / heightMapDimensions.y);
    vec2 texelSize = 1.0 / textureSize(HeightMapTexture, 0);
    float height = texture(HeightMapTexture, normalizedCoords + (texelSize * 0.5)).r;
    float roadMask = texture(RoadMaskTexture, normalizedCoords).r;

    float posY = height * HEIGHTMAP_SCALE_Y;

    // Skip road
    if (roadMask > 0.6) {
        return;
    }

    // Skip underwater
    if (posY < u_waterHeight) {
        return;
    }

    float rr = Rand(vec2(gid.y, gid.x));
    float amt = 0.05;
    posY += rr * amt - (amt / 2);
    vec3 basePos = vec3(posX, posY, posZ);

    // Frustum cull
    if (!IntersectsSphere(basePos, bladeHeight * 10, viewportIndex)) {
        return;
    }

    // Get screen uv
    vec2 biasedScreenUV = WorldToScreen(basePos, projectionView, viewportPos, viewportSize);
    biasedScreenUV = clamp(biasedScreenUV, vec2(0.0), vec2(1.0));

    // Early reject without sampling world position
    if (any(lessThan(biasedScreenUV, vec2(0.0))) || any(greaterThan(biasedScreenUV, vec2(1.0)))) return;

    // Occlusion cull
    float depth = texture(u_depthTexture, biasedScreenUV).r;
    vec3 sceneWorldPos = WorldPosFromDepth_GL(biasedScreenUV, depth, inverseProjectionView);

    float sceneDistanceToCamera = length(sceneWorldPos - viewPos);
    float baseDistanceToCamera = length(basePos - viewPos);
    float boundingRadius = bladeHeight;

    if ((baseDistanceToCamera - boundingRadius) > sceneDistanceToCamera) {
        return;
    }

    // this may be faster?

    // float sceneDepth = texture(u_depthTexture, biasedScreenUV).r;
    //
    // // offset point toward camera by blade height bounding radius
    // vec3 dirToCamera = normalize(viewPos - basePos);
    // vec3 testPos = basePos + (dirToCamera * bladeHeight);
    //
    // // project to clip space
    // vec4 clipPos = projectionView * vec4(testPos, 1.0);
    // if (clipPos.w <= 0.0) return;
    //
    // float ndcZ = clipPos.z / clipPos.w;
    //
    // float grassDepth = ndcZ;
    // // if (grassDepth > sceneDepth) return;
    // // if (grassDepth < sceneDepth) return; // revere Z


    // Don't sample skybox
    //if (sceneWorldPos.x == 0.0 && sceneWorldPos.y == 0.0 && sceneWorldPos.z == 0.0) {
    //    return;
    //}

    // Jitter the positon
    //float jitterX = (Rand(vec2(basePos.x, basePos.z)) - 0.5) * 0.1;
    //float jitterZ = (Rand(vec2(basePos.z, basePos.x)) - 0.5) * 0.1;
    //basePos.x += jitterX;
    //basePos.z += jitterZ;

    // Append
    uint baseIndex = atomicAdd(drawCmd.count, 24);
    uint indx = baseIndex / 24; // there are 24 indices per blade
    bladePositions[indx] = vec4(basePos, 0);
}
