#version 460

//#if ENABLE_BINDLESS == 1
#extension GL_ARB_bindless_texture : enable
#extension GL_EXT_nonuniform_qualifier : enable
readonly restrict layout(std430, binding = 0) buffer textureSamplersBuffer { uvec2 textureSamplers[]; };
//#endif

#include "../common/lighting.glsl"
#include "../common/post_processing.glsl"
#include "../common/types.glsl"
#include "../common/util.glsl"
#include "../common/constants.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout (binding = 0) uniform sampler2D BaseColorTexture;
layout (binding = 1) uniform sampler2D NormalTexture;
layout (binding = 2) uniform sampler2D RMATexture;
layout (binding = 3) uniform sampler2D u_depthTexture;
layout (binding = 6) uniform sampler2D EmissiveTexture;
layout (binding = 7) uniform sampler2D FlashlightCookieTexture;
layout (binding = 8) uniform sampler2DArray FlashlighShadowMapArrayTexture;
layout (binding = 9) uniform samplerCubeArray shadowMapArray;
layout (binding = 10) uniform sampler2DArray u_shadowMapCascadeArray;
layout (binding = 11) uniform sampler2D IndirectDiffuseTexture;

uniform float u_viewportWidth;
uniform float u_viewportHeight;
uniform int u_tileXCount;
uniform int u_tileYCount;
uniform int u_editorLighting;
uniform int u_ambientLightingBoost;

uniform vec3 u_lightVolumeOffset;
uniform vec3 u_lightVolumeWorldSize;
uniform float u_lightVolumeSpacing;
uniform float u_oceanHeight;


// GI
uniform vec3 u_probeOffset;
uniform float u_probeSpacing;
uniform int u_probeCount;
uniform int u_probeCountX;
uniform int u_probeCountY;
uniform int u_probeCountZ;
uniform bool u_sampleProbes;

layout(rgba16f, binding = 0) uniform image2D outputImage;

readonly restrict layout(std430, binding = 1) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };
readonly restrict layout(std430, binding = 4) buffer lightsBuffer       { Light lights[]; };
readonly restrict layout(std430, binding = 5) buffer tileLightsBuffer   { TileLights tileLights[];   };

layout(std430, binding = 7)  readonly restrict  buffer tileChristmasLightsBuffer  { TileInstanceData tileChristmasLights[]; };
layout(std430, binding = 8)  readonly restrict  buffer ChristmasLightsBuffer      { ChristmasLight christmasLights[]; };
layout(std430, binding = 9)  readonly restrict  buffer ChristmasLightsIndexBuffer { uint globalChristmasLightIndices[]; };

// Moon lighting
uniform float u_cascadeFarPlane = 256.0;
uniform float u_cascadePlaneDistances[16];
#include "../common/moon_lighting.glsl"

vec3 retroBRDF(vec3 albedo, vec3 L, vec3 V, vec3 N, float mask, float retroSharpness, float retroGain) {
    float ndotl = max(dot(N, L), 0.0);          // no light from back
    float lv = max(dot(L, V), 0.0);             // retro alignment
    float lobe = pow(lv, retroSharpness);       // tight lobe around L V

    // Schlick like fresnel using L.V to boost at grazing/near align
    float F = mix(0.02, 1.0, pow(1.0 - lv, 5.0));

    // micro prism sparkle (optional)
    // hash = per pixel blue noise or bayer, anim with time for sparkle
    float hash = fract(sin(dot(gl_GlobalInvocationID.xy, vec2(12.9898,78.233))) * 43758.5453);
    float sparkle = step(1.0 - lobe, hash);     // sparse bright specks
    float micro = mix(1.0, 1.0 + 4.0 * sparkle, 0.15);

    float retro = mask * ndotl * lobe * F * retroGain * micro;

    return albedo * retro;
}

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(outputImage);

    // Don't process out of bounds pixels
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;

    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportDataArr[viewportIndex]);

    // Inputs
    vec4 baseColor = texture(BaseColorTexture, screenUV);
    vec4 normal = texture(NormalTexture, screenUV);
    vec4 rma = texture(RMATexture, screenUV);

    float sssRadius = texture(EmissiveTexture, screenUV).a;

    float sssIntensity = 5;

    vec3 emssiveColor = texture(EmissiveTexture, screenUV).rgb;
    baseColor.rgb += emssiveColor.rgb;

    // Don't apply lighting to skybox
    if (normal.x == 0.0 && normal.y == 0.0 && normal.z == 0.0) {
        //imageStore(outputImage, px, baseColor);
        return;
    }

    // Gamma-correct the base color
    vec3 gammaBaseColor = pow(baseColor.rgb, vec3(2.2));

    float roughness = rma.r;
    float metallic = rma.g;
    float ao = rma.b;

    vec2 renderTargetSize = vec2(rendererData.gBufferWidth, rendererData.gBufferHeight);
    int splitScreenMode = rendererData.splitscreenMode;

    //float clipSpaceXMin = viewportData[viewportIndex].clipSpaceXMin;
    //float clipSpaceXMax = viewportData[viewportIndex].clipSpaceXMax;
    //float clipSpaceYMin = viewportData[viewportIndex].clipSpaceYMin;
    //float clipSpaceYMax = viewportData[viewportIndex].clipSpaceYMax;
    mat4 inverseProjection = viewportDataArr[viewportIndex].inverseProjectionReverseZ;
    mat4 inverseProjectionView = viewportDataArr[viewportIndex].inverseProjectionViewReverseZ;
    mat4 inverseView = viewportDataArr[viewportIndex].inverseView;
    mat4 viewMatrix = viewportDataArr[viewportIndex].view;
    vec3 viewPos = inverseView[3].xyz;
    bool thisViewportIsInShop = bool(viewportDataArr[viewportIndex].isInShop);

    // Position from depth reconstruction
    float depth = texelFetch(u_depthTexture, px, 0).r;
    vec3 worldPos = ReconstructWorldPos(viewportUV, depth, inverseProjectionView);

    float fragDistance = distance(viewPos, worldPos);

    // Tile params
    uint tileIndex = gl_WorkGroupID.y * u_tileXCount + gl_WorkGroupID.x;
	uint lightCount = tileLights[tileIndex].lightCount;

    float sssStrength = 0.03;


    vec3 sssDebug = vec3(0);

    vec3 viewDir = normalize(viewPos - worldPos);
    vec3 subColor = Saturate(gammaBaseColor.rgb, 1.5);

    // Direct light
    vec3 directLighting = vec3(0);

    for (int i = 0; i < lightCount; i++) {
        int lightIndex = int(tileLights[tileIndex].lightIndices[i]);

    //for (int i = 2; i < 9; i++) {
	//	int lightIndex = i;

        Light light = lights[lightIndex];
        vec3 lightPosition = vec3(light.posX, light.posY, light.posZ);
        vec3 lightColor =  vec3(light.colorR, light.colorG, light.colorB);
        float lightStrength = light.strength;
        float lightRadius = light.radius;

        float shadow = ShadowCalculation(lightIndex, lightPosition, lightRadius, worldPos, viewPos, normal.xyz, shadowMapArray);
        vec3 directLight = GetDirectLighting(lightPosition, lightColor, lightRadius, lightStrength, normal.xyz, worldPos, gammaBaseColor.rgb, roughness, metallic, viewPos) * shadow;

        if (light.iesTextureIndex != 0) {
            sampler2D iesSampler = sampler2D(textureSamplers[(light.iesTextureIndex)]);
            float candelas = ApplyIESProfile(worldPos, light, iesSampler);
            directLight *= candelas;
        }

        directLighting += directLight;


        // Subsurface scattering (back lit Translucency from thickness map)
        if (sssRadius > 0 && sssRadius < 0.99) {
            float lightAttenuation = smoothstep(lightRadius, 0, length(lightPosition - worldPos));

            float thickness = sssRadius;
            vec3 L = normalize(lightPosition - worldPos);
            float backScatter = pow(max(0.0, dot(viewDir, -L)), 12.0) * thickness;

            vec3 sssFinal = subColor * backScatter * sssIntensity;
            // Not sure why you used this in the first place, but u removed it coz it fucked with the dreads
            // directLighting += sssFinal * lightAttenuation * shadow;
        }
    }

    // Christmas lights Direct light
    uint christmasLightCount = tileChristmasLights[tileIndex].count; // Num of Chrissy lights in this tile
    uint christmasLightOffset = tileChristmasLights[tileIndex].offset;

    for (uint i = 0; i < christmasLightCount; ++i) {
        uint idx = globalChristmasLightIndices[christmasLightOffset + i];
        vec3 lightPosition = christmasLights[idx].position.xyz;
        vec3 lightColor = christmasLights[idx].color.rgb;
        float lightRadius = 0.1;
        float lightStrength = 1.0;

        directLighting += GetDirectLighting(lightPosition, lightColor, lightRadius, lightStrength, normal.xyz, worldPos, gammaBaseColor.rgb, roughness, metallic, viewPos);
    }


    for (int i = 0; i < 2; i++) {

        // Dont apply flashlight too close
        //if (fragDistance < 0.01) {
        //    continue;
        //}

        float flashlightModifer = viewportDataArr[i].flashlightModifer;
        if (flashlightModifer > 0.05) {
            mat4 flashlightProjectionView = viewportDataArr[i].flashlightProjectionView;
            vec4 flashlightDir = viewportDataArr[i].flashlightDir;
            vec4 flashlightPosition = viewportDataArr[i].flashlightPosition;
            vec3 flashlightViewPos = viewportDataArr[i].inverseView[3].xyz;
            vec3 playerForward = -normalize(viewportDataArr[i].inverseView[2].xyz);
            int layerIndex = i;
		    vec3 spotLightPos = flashlightPosition.xyz;
            vec3 camightRight = normalize(viewportDataArr[i].inverseView[0].xyz);
		    vec3 spotLightDir = flashlightDir.xyz;
            vec3 spotLightColor = GetFlashLightColor();

            float spotLightRadius = 25.0;
            float spotLightStregth = 4.5;

            if (worldPos.y < u_oceanHeight - 0.1) {
                spotLightStregth *= 2.0;
            }

            // Prevent flashlight being drawn on the back of your head when viewed by another player
            if (i != viewportIndex) {
                spotLightPos += spotLightDir * 0.2;

                // and weaken it for other players
                spotLightColor *= 0.825;
            }

            float innerAngle = cos(radians(5.0 * flashlightModifer));
            float outerAngle = cos(radians(20.5));

            bool thisFlashlightIsInShop = bool(viewportDataArr[i].isInShop);

            if (thisFlashlightIsInShop) {
                spotLightRadius = 8;
                outerAngle = cos(radians(50.0));
            }

            //if (worldPos.y < 10) {
            //    spotLightStregth = 25;
            //}

            mat4 lightProjectionView = flashlightProjectionView;
            vec3 spotLighting = GetSpotlightLighting(spotLightPos, spotLightDir, spotLightColor, spotLightRadius, spotLightStregth, innerAngle, outerAngle, normal.xyz, worldPos, gammaBaseColor.rgb, roughness, metallic, flashlightViewPos, lightProjectionView);


            //if (baseColor.rgb == vec3(1, 0, 0)) {
            //    vec3 L = normalize(spotLightPos - worldPos);
            //    vec3 V = normalize(viewPos - worldPos);
            //    float mask = 1; // 0 or 1
            //    float retroSharpness = 64; // 64 to 2048
            //    float retroGain = 10; // 5 to 30
            //    spotLighting = retroBRDF(baseColor.rgb, L, V, normal.xyz, mask, retroSharpness, retroGain);
            //}


            vec4 FragPosLightSpace = lightProjectionView * vec4(worldPos, 1.0);
            float shadow = 0;


            // If this flashlight is in the shop AND this flashlight belongs to the current viewport
            if (i == viewportIndex && thisFlashlightIsInShop) {
                // do nothing
            }
            else {
                shadow = SpotlightShadowCalculation(FragPosLightSpace, normal.xyz, spotLightDir, worldPos, spotLightPos, flashlightViewPos, FlashlighShadowMapArrayTexture, layerIndex);
            }

            //shadow = 0;

            // Subsurface scattering
            if (false) { // <------------------------- THIS BLOCK SEEMS FUCKED?
                vec3 radius = vec3(sssRadius);
                vec3 subColor = Saturate(baseColor.rgb, 1.5);
                vec3 L = spotLightDir;
                float NdotL = max(dot(normal.xyz, L), 0.0);
                vec3 sss = 0.2 * exp(-3.0 * abs(NdotL) / (radius + 0.001));
                vec3 sssColor = subColor * radius * sss * sssStrength;
                float lightAttenuation = smoothstep(spotLightRadius, 0.0, fragDistance) * spotLightStregth;
                spotLighting += sssColor * lightAttenuation * (1 - shadow);
            }
            // Cookie corretion

            vec3 cookie = ApplyCookie(lightProjectionView, worldPos, spotLightPos, spotLightColor, spotLightRadius, FlashlightCookieTexture);

            float cookieStartDistance = 1.0;
            float cookieEndDistance = 10.0;
            float cookieDistanceExponent = 2;
            float cookieMinValue = 0.5;
            float cookieMaxValue = 5.0;
            float cookieDistScale;
            if(fragDistance <= cookieStartDistance) {
                cookieDistScale = cookieMinValue;
            } else if(fragDistance >= cookieEndDistance) {
                cookieDistScale = cookieMaxValue;
            } else {
                float t = (fragDistance - cookieStartDistance) / (cookieEndDistance - cookieStartDistance);
                cookieDistScale = mix(cookieMinValue, cookieMaxValue, pow(t, cookieDistanceExponent));
            }
            spotLighting *= cookieDistScale;
            //spotLighting *= spotLightColor;

            spotLighting *= vec3(1 - shadow);


         //   cookie *= 10;

            if (!thisFlashlightIsInShop) {
                spotLighting *= cookie;
            }

            directLighting += vec3(spotLighting) * flashlightModifer;
        }
    }

    // Moon light
    vec3 moonlightDir = rendererData.moonLightDir.xyz;
    vec3 moonLighting = vec3(0.0);
    float moonNdotL = dot(normal.xyz, moonlightDir);

    if (moonNdotL > 0.0) {
        vec3 shadow = ShadowCalculationCSM(worldPos, normal.xyz, moonlightDir, viewMatrix, viewportIndex);

        if (any(greaterThan(shadow, vec3(0.0)))) {
            moonLighting = GetDirectionalLighting(moonlightDir, MOON_LIGHT_COLOR, MOON_LIGHT_STRENGTH, normal.xyz, worldPos, gammaBaseColor.rgb, roughness, metallic, viewPos);
            moonLighting *= shadow;

            // DO THIS WHEN YOU DO MATERIAL RESOLVE FOR FOLLAGE
            // vec3 radius = vec3(sssRadius);
            // vec3 L = moonlightDir;
            // float NdotL = max(dot(normal.xyz, L), 0.0);
            // vec3 sss = 0.2 * exp(-3.0 * abs(NdotL) / (radius + 0.001));
            // vec3 sssColor = subColor * radius * sss * sssStrength;
            // moonLighting += sssColor * shadow * 0.5; // OG
        }
    }
    




    if (viewportDataArr[viewportIndex].flashlightModifer > 0.1) {
        vec3 offset = viewportDataArr[viewportIndex].cameraForward.xyz * 0.001;
        vec3 spotLightPos = viewPos + offset;
        vec3 spotLightDir = viewportDataArr[viewportIndex].flashlightDir.xyz;
        vec3 spotLightColor = vec3(0.9, 0.95, 1.1);

        //spotLightColor = vec3(1.00, 0.7799999713897705, 0.5289999842643738);


        spotLightColor = mix(spotLightColor, vec3(1, 0.7799999713897705, 0.5289999842643738), 0.5);

        //float spotLightRadius = 0.0765;
        float spotLightRadius = 0.165;
        float spotLightStregth = 10.0;
        float innerAngle = cos(radians(00.0 * viewportDataArr[viewportIndex].flashlightModifer));
        float outerAngle = cos(radians(40.0));

        mat4 lightProjectionView = viewportDataArr[viewportIndex].flashlightProjectionView;
        vec4 flashlightDir = viewportDataArr[viewportIndex].flashlightDir;
        vec4 flashlightPosition = viewportDataArr[viewportIndex].flashlightPosition;
        vec3 flashlightViewPos = viewportDataArr[viewportIndex].inverseView[3].xyz;

        vec3 re7Lighting = GetSpotlightLighting(spotLightPos, spotLightDir, spotLightColor, spotLightRadius, spotLightStregth, innerAngle, outerAngle, normal.xyz, worldPos, gammaBaseColor.rgb, roughness, metallic, flashlightViewPos, lightProjectionView);
        directLighting += re7Lighting;
    }

    // Alpha
    float finalAlpha = baseColor.a;





    // Composite
    vec3 finalColor = directLighting.rgb + moonLighting;

    // Ambient occlusion
    finalColor *= ao;

    // Distance fog
    float fogStartDist = 5;
    float fogEndDist = 25;
    float fogCurve = 5;
    float fogStrength = 1.0;
    vec3 fogColor = vec3(0,0,0);
    float distanceFogFactor = pow(clamp((fragDistance - fogStartDist) / max(fogEndDist - fogStartDist, 1e-6), 0.0, 1.0), max(fogCurve, 1e-6));
    float fogAlpha = distanceFogFactor * fogStrength;
    finalColor = mix(finalColor, fogColor, fogAlpha);

    // Indirect diffuse
    if (u_sampleProbes) {
        vec3 probeIrradiance = texture(IndirectDiffuseTexture, screenUV).rgb;
        vec3 diffuseAlbedo = gammaBaseColor.rgb * (1.0 - metallic);
        float indirectDiffuseScale = 1.0;
        vec3 indirectDiffuse = probeIrradiance * diffuseAlbedo * ao * indirectDiffuseScale;
        finalColor += indirectDiffuse;
    }

    // Premultiply alpha
    finalColor.rgb = finalColor.rgb * finalAlpha;
    vec4 outputColor = vec4(finalColor, finalAlpha);

   // outputColor.rgb = vec3(sssRadius);

   // outputColor.rgb = directLighting;

    imageStore(outputImage, px, outputColor);
    
    
    //float thickness = texture(EmissiveTexture, screenUV).a;
    //imageStore(outputImage, px, vec4(vec3(thickness), 1));
    //imageStore(outputImage, px, vec4(vec3(sssDebug), 1));
}