#pragma once

#include <cstdint>

namespace Hell::ResourceManagement {

enum class ResourceType : uint16_t {
    OPENGL_CUBEMAP_FRAME_BUFFER,
    OPENGL_CUBEMAP_VIEW,
    OPENGL_GENERIC_MESH,
    OPENGL_MESH_BUFFER,
    OPENGL_TEXTURE,
    OPENGL_TEXTURE_3D,
    OPENGL_TEXTURE_ARRAY,
    VULKAN_GENERIC_MESH,
    VULKAN_MESH_BUFFER,
    VULKAN_TEXTURE,
    OPENGL_SHADER,
    OPENGL_SSBO,
    OPENGL_FRAME_BUFFER,
    OPENGL_SHADOW_CUBE_MAP_ARRAY,
    OPENGL_SHADOW_MAP,
    OPENGL_SHADOW_MAP_ARRAY,
    UNDEFINED
};

}
