
#define SSBO_IDX_SAMPLERS       0
#define SSBO_IDX_MATERIALS      1
#define SSBO_IDX_RENDERER_DATA  2
#define SSBO_IDX_VIEWPORT_DATA  3
#define SSBO_IDX_INSTANCE_DATA  4
#define SSBO_IDX_LIGHTS         5

// Pass local SSBO bindings
#define SSBO_IDX_PASS_LOCAL_0                  6
#define SSBO_IDX_GLASS_INSTANCE_DATA           SSBO_IDX_PASS_LOCAL_0
#define SSBO_IDX_SPRITE_SHEET_INSTANCE_DATA    SSBO_IDX_PASS_LOCAL_0
#define SSBO_IDX_POINT_SHADOW_FACE_DATA         SSBO_IDX_PASS_LOCAL_0
#define SSBO_IDX_GLASS_LIGHT_RANGES             7
#define SSBO_IDX_GLASS_LIGHT_INDICES            8

#define TEX_IDX_SHADOW_MAP_FLASHLIGHT 0
#define TEX_IDX_SHADOW_MAP_HI_RES     1
#define TEX_IDX_SHADOW_MAP_LOW_RES    2
#define TEX_IDX_SHADOW_MAP_CSM        3
