#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct DrawArraysCommand {
    uint count;
    uint instanceCount;
    uint firstVertex;
    uint baseInstance;
};

layout(std430, binding = 6) readonly buffer BubblePositionsBuffer { vec4 bubblePositions[]; }; // unused atm
layout(std430, binding = 7) readonly buffer ParticleCountBuffer   { uint particleCount; };
layout(std430, binding = 8) buffer IndirectCommand                { DrawArraysCommand command; };

void main() {
    if (gl_GlobalInvocationID.x == 0) {
        command.count = 6;
        command.instanceCount = particleCount;
        command.firstVertex = 0;
        command.baseInstance = 0;
    }
}
