#version 460

#extension GL_ARB_bindless_texture : enable
#extension GL_EXT_nonuniform_qualifier : enable

#include "../../common/constants.glsl"
#include "../../common/lighting.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/post_processing.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout (rgba16f, binding = 0) uniform image2D u_outputImage;
layout (binding = 1) uniform sampler2D u_baseColorMetallicTexture;
layout (binding = 2) uniform sampler2D u_normalXYRoughnessMiscTexture;
layout (binding = 3) uniform sampler2D u_velocityXYOcclusionSubSurfaceTexture;
layout (binding = 4) uniform sampler2D u_depthTexture;
layout (binding = 5) uniform sampler2D u_indirectDiffuseTexture;

layout (binding = 7) uniform sampler2D u_flashlightCookieTexture;
layout (binding = 8) uniform sampler2DArray u_flashlighShadowMapArrayTexture;
layout (binding = 9) uniform samplerCubeArray u_shadowMapArray;
layout (binding = 10) uniform sampler2DArray u_shadowMapCascadeArray;

readonly restrict layout(std430, binding = 0) buffer textureSamplersBuffer { uvec2 textureSamplers[]; };
readonly restrict layout(std430, binding = 1) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };
readonly restrict layout(std430, binding = 3) buffer renderItemsBuffer  { RenderItem renderItems[]; };
readonly restrict layout(std430, binding = 4) buffer lightsBuffer       { Light lights[]; };
readonly restrict layout(std430, binding = 5) buffer tileLightsBuffer   { TileLights tileLights[];   };

// TODO: dont hardcode
uniform float u_oceanHeight = 30;

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(u_outputImage);
    
    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportDataArr[viewportIndex]);

    vec4 normalXYRoughnessMisc = texture(u_normalXYRoughnessMiscTexture, screenUV);
    vec3 normal = DecodeNormal(normalXYRoughnessMisc.rg);
    float roughness = normalXYRoughnessMisc.b;
    float misc = normalXYRoughnessMisc.a;

    vec4 baseColorMetallic = texture(u_baseColorMetallicTexture, screenUV);
    vec3 baseColor = baseColorMetallic.rgb;
    float metallic = baseColorMetallic.a;
    vec3 linearBaseColor = pow(baseColor.rgb, vec3(2.2)); // baseColor.rgb * baseColor.rgb;

    vec4 velocityXYOcclusionSubSurface = texture(u_velocityXYOcclusionSubSurfaceTexture, screenUV).rgba;
    float ao =velocityXYOcclusionSubSurface.b;
    float subSurface = velocityXYOcclusionSubSurface.a;
    vec2 velocity = velocityXYOcclusionSubSurface.rg;


    ViewportData viewportData = viewportDataArr[viewportIndex];
    mat4 inverseProjection = viewportData.inverseProjection;
    mat4 inverseProjectionViewReverseZ = viewportData.inverseProjectionViewReverseZ;
    mat4 inverseView = viewportData.inverseView;
    mat4 viewMatrix = viewportData.view;
    vec3 viewPos = viewportData.viewPos.xyz;
    bool thisViewportIsInShop = bool(viewportData.isInShop);

    float depth = texelFetch(u_depthTexture, px, 0).r;
    vec3 worldPos = ReconstructWorldPos(viewportUV, depth, inverseProjectionViewReverseZ);

    float fragDistance = distance(worldPos, viewPos);

    vec3 F0 = mix(vec3(0.04), linearBaseColor, metallic);

    vec3 directLighting = vec3(0.0);
    for (int i = 2; i < 4; i++) {
        int lightIndex = i; //int(tileLights[tileIndex].lightIndices[i]);

        Light light = lights[lightIndex];
        vec3 lightPosition = vec3(light.posX, light.posY, light.posZ);
        vec3 lightColor =  vec3(light.colorR, light.colorG, light.colorB);
        float lightStrength = light.strength;
        float lightRadius = light.radius;

        float shadow = ShadowCalculation(lightIndex, lightPosition, lightRadius, worldPos.xyz, viewPos, normal.xyz, u_shadowMapArray);
        vec3 directLight = GetDirectLighting(lightPosition, lightColor, lightRadius, lightStrength, normal.xyz, worldPos.xyz, linearBaseColor.rgb, roughness, metallic, viewPos) * shadow;

        if (light.iesTextureIndex != 0) {
            sampler2D iesSampler = sampler2D(textureSamplers[(light.iesTextureIndex)]);
            float candelas = ApplyIESProfile(worldPos.xyz, light, iesSampler);
            directLight *= candelas;
        }

        directLighting += directLight;
    }


    for (int i = 0; i < 2; i++) {
        float flashlightModifer = viewportDataArr[i].flashlightModifer;

        if (flashlightModifer > 0.05) {
            mat4 flashlightProjectionView = viewportDataArr[i].flashlightProjectionView;
            vec4 flashlightDir = viewportDataArr[i].flashlightDir;
            vec4 flashlightPosition = viewportDataArr[i].flashlightPosition;
            vec3 flashlightViewPos = viewportDataArr[i].inverseView[3].xyz;
            vec3 playerForward = -normalize(viewportDataArr[i].inverseView[2].xyz);
            int layerIndex = i;
		    vec3 spotLightPos = flashlightPosition.xyz;
            vec3 camightRight = normalize(viewportDataArr[i].inverseView[0].xyz);
		    vec3 spotLightDir = flashlightDir.xyz;
            vec3 spotLightColor = GetFlashLightColor();

            float spotLightRadius = 25.0;
            float spotLightStregth = 4.5;

            if (worldPos.y < u_oceanHeight - 0.1) {
                spotLightStregth *= 2.0;
            }

            // Prevent flashlight being drawn on the back of your head when viewed by another player
            if (i != viewportIndex) {
                spotLightPos += spotLightDir * 0.2;

                // and weaken it for other players
                spotLightColor *= 0.825;
            }

            float innerAngle = cos(radians(5.0 * flashlightModifer));
            float outerAngle = cos(radians(20.5));

            bool thisFlashlightIsInShop = bool(viewportDataArr[i].isInShop);

            if (thisFlashlightIsInShop) {
                spotLightRadius = 8;
                outerAngle = cos(radians(50.0));
            }

            mat4 lightProjectionView = flashlightProjectionView;
            vec3 spotLighting = GetSpotlightLighting(spotLightPos, spotLightDir, spotLightColor, spotLightRadius, spotLightStregth, innerAngle, outerAngle, normal.xyz, worldPos.xyz, linearBaseColor.rgb, roughness, metallic, flashlightViewPos, lightProjectionView);

            vec4 FragPosLightSpace = lightProjectionView * vec4(worldPos, 1.0);
            float shadow = 0;

            // If this flashlight is in the shop AND this flashlight belongs to the current viewport
            if (i == viewportIndex && thisFlashlightIsInShop) {
                // do nothing
            }
            else {
                shadow = SpotlightShadowCalculation(FragPosLightSpace, normal.xyz, spotLightDir, worldPos, spotLightPos, flashlightViewPos, u_flashlighShadowMapArrayTexture, layerIndex);
            }

            vec3 cookie = ApplyCookie(lightProjectionView, worldPos, spotLightPos, spotLightColor, spotLightRadius, u_flashlightCookieTexture);

            float cookieStartDistance = 1.0;
            float cookieEndDistance = 10.0;
            float cookieDistanceExponent = 2;
            float cookieMinValue = 0.5;
            float cookieMaxValue = 5.0;
            float cookieDistScale;
            if(fragDistance <= cookieStartDistance) {
                cookieDistScale = cookieMinValue;
            } else if(fragDistance >= cookieEndDistance) {
                cookieDistScale = cookieMaxValue;
            } else {
                float t = (fragDistance - cookieStartDistance) / (cookieEndDistance - cookieStartDistance);
                cookieDistScale = mix(cookieMinValue, cookieMaxValue, pow(t, cookieDistanceExponent));
            }
            spotLighting *= cookieDistScale;

            spotLighting *= vec3(1 - shadow);

            if (!thisFlashlightIsInShop) {
                spotLighting *= cookie;
            }

            directLighting += vec3(spotLighting) * flashlightModifer;
        }
    }

    vec3 indirectDiffuse = vec3(0);
    bool u_sampleProbes = true;
    if (u_sampleProbes) {
        vec3 probeIrradiance = texture(u_indirectDiffuseTexture, screenUV).rgb;
        vec3 diffuseAlbedo = linearBaseColor.rgb * (1.0 - metallic);
        float indirectDiffuseScale = 1.0;
        indirectDiffuse = probeIrradiance * diffuseAlbedo * indirectDiffuseScale;
    }

    vec3 finalColor = (directLighting + indirectDiffuse) * ao;

    //finalColor = indirectDiffuse;

    imageStore(u_outputImage, px, vec4(finalColor, 1));
}