#version 450 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D u_lightingImage;
layout(binding = 1) uniform sampler2D u_scratchTexture;

#define FXAA_REDUCE_MIN (1.0 / 128.0)
#define FXAA_REDUCE_MUL (1.0 / 8.0)
#define FXAA_SPAN_MAX   8.0

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 res = imageSize(u_lightingImage);

    if (px.x >= res.x || px.y >= res.y) return;

    vec2 texelSize = 1.0 / vec2(res);
    vec2 uv = (vec2(px) + 0.5) * texelSize;

    // Calculate neighbor uv coordinates
    vec2 v_rgbNW = uv + (vec2(-1.0, -1.0) * texelSize);
    vec2 v_rgbNE = uv + (vec2(1.0, -1.0) * texelSize);
    vec2 v_rgbSW = uv + (vec2(-1.0, 1.0) * texelSize);
    vec2 v_rgbSE = uv + (vec2(1.0, 1.0) * texelSize);
    vec2 v_rgbM  = uv;

    vec3 rgbNW = texture(u_scratchTexture, v_rgbNW).xyz;
    vec3 rgbNE = texture(u_scratchTexture, v_rgbNE).xyz;
    vec3 rgbSW = texture(u_scratchTexture, v_rgbSW).xyz;
    vec3 rgbSE = texture(u_scratchTexture, v_rgbSE).xyz;
    vec4 texColor = texture(u_scratchTexture, v_rgbM);
    vec3 rgbM  = texColor.xyz;

    vec3 luma = vec3(0.299, 0.587, 0.114);
    float lumaNW = dot(rgbNW, luma);
    float lumaNE = dot(rgbNE, luma);
    float lumaSW = dot(rgbSW, luma);
    float lumaSE = dot(rgbSE, luma);
    float lumaM  = dot(rgbM,  luma);

    float lumaMin = min(lumaM, min(min(lumaNW, lumaNE), min(lumaSW, lumaSE)));
    float lumaMax = max(lumaM, max(max(lumaNW, lumaNE), max(lumaSW, lumaSE)));

    vec2 dir;
    dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));
    dir.y =  ((lumaNW + lumaSW) - (lumaNE + lumaSE));

    float dirReduce = max((lumaNW + lumaNE + lumaSW + lumaSE) * (0.25 * FXAA_REDUCE_MUL), FXAA_REDUCE_MIN);
    float rcpDirMin = 1.0 / (min(abs(dir.x), abs(dir.y)) + dirReduce);

    dir = min(vec2(FXAA_SPAN_MAX), max(vec2(-FXAA_SPAN_MAX), dir * rcpDirMin)) * texelSize;

    // First pass sub-pixel blur
    vec3 rgbA = 0.5 * (texture(u_scratchTexture, uv + dir * (1.0 / 3.0 - 0.5)).xyz + texture(u_scratchTexture, uv + dir * (2.0 / 3.0 - 0.5)).xyz);

    // Second pass wider blur
    vec3 rgbB = rgbA * 0.5 + 0.25 * ( texture(u_scratchTexture, uv + dir * -0.5).xyz + texture(u_scratchTexture, uv + dir * 0.5).xyz);

    float lumaB = dot(rgbB, luma);

    vec4 finalColor;

    if ((lumaB < lumaMin) || (lumaB > lumaMax)) {
        finalColor = vec4(rgbA, texColor.a);
    } 
    else {
        finalColor = vec4(rgbB, texColor.a);
    }

    imageStore(u_lightingImage, px, finalColor);
}