#version 450
#include "../../common/constants.glsl"
#include "../../common/ddgi.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(std430, binding = 4) buffer ProbeStateBuffer          { ProbeState probeStates[]; };
layout(std430, binding = 5) readonly buffer DDGIVolumeBuffer { DDGIVolume volume; };
layout(std430, binding = 6) readonly buffer rendererDataBuffer { RendererData rendererData; };
layout(std430, binding = 7) readonly buffer viewportDataBuffer { ViewportData viewportData[]; };

layout (binding = 0) uniform sampler2DMS u_depthTextureMS;
layout (binding = 1) uniform sampler2DMS u_normalTextureMS;
layout (binding = 2) uniform sampler2D u_normalTexture;
layout (binding = 3) uniform sampler2D u_depthTexture;

uniform bool u_msaaRenderer;
uniform bool u_octNormals;
uniform vec3 u_viewPos; // THIS MUST BE COMPUTED FROM SCREEN COORDS FOR PLAYESR 2, 3, & 4 to work

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy) * 4; // scale by 4 for quarter-res sampling
    ivec2 gBufferSize = textureSize(u_normalTexture, 0);

    if (pixelCoords.x >= gBufferSize.x || pixelCoords.y >= gBufferSize.y) return;

    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(pixelCoords, gBufferSize, rendererData.splitscreenMode);

    // Read DDGIVolume
    vec3 probeOffset = volume.origin;
    ivec3 probeCounts = volume.probeCounts;
    float probeSpacing = volume.probeSpacing;
    int totalProbes = volume.totalProbes;

    // Normal
    vec3 fragNormal = vec3(0);
    if (u_msaaRenderer) {
        fragNormal = texelFetch(u_normalTextureMS, pixelCoords, 0).xyz;
    }
    else {
        fragNormal = texelFetch(u_normalTexture, pixelCoords, 0).xyz;
        if (u_octNormals) {
            fragNormal = DecodeNormal(fragNormal.rg);
        }
    }

    if (dot(fragNormal, fragNormal) < 0.0001) return;

    // Viewport UV
    ivec2 px = ivec2(gl_GlobalInvocationID.xy) * 4; // scale by 4 for quarter-res sampling
    ivec2 resolution = textureSize(u_depthTexture, 0);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(resolution);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportData[viewportIndex]);

    // World pos
    vec3 fragPosition;

    if (u_msaaRenderer) {
        float depth = texelFetch(u_depthTextureMS, px, 0).r;
        vec4 clip = vec4(viewportUV * 2.0 - 1.0, depth, 1.0);
        vec4 worldH = viewportData[viewportIndex].inverseProjectionViewReverseZ * clip;
        fragPosition = worldH.xyz / worldH.w;
    }
    else {
        float depth = texelFetch(u_depthTexture, px, 0).r;
        vec4 clip = vec4(viewportUV * 2.0 - 1.0, depth, 1.0);
        vec4 worldH = viewportData[viewportIndex].inverseProjectionView * clip;
        fragPosition = worldH.xyz / worldH.w;
    }


    vec3 surfaceBias = DDGIGetSurfaceBias(fragPosition, fragNormal, u_viewPos); // Uses PROBE_NORMAL_BIAS and PROBE_VIEW_BIAS
    vec3 biasedWorldPosition = fragPosition + surfaceBias;

    ivec3 base = DDGIGetBaseProbeGridCoords(biasedWorldPosition, volume);

    ivec3 maxCoords = probeCounts - ivec3(2);
    if (any(lessThan(base, ivec3(0))) || any(greaterThan(base, maxCoords))) return;

    // Mark all 8 probes in the trilinear volume as visible
    for (int dy = 0; dy <= 1; dy++) {
        for (int dz = 0; dz <= 1; dz++) {
            for (int dx = 0; dx <= 1; dx++) {
                ivec3 pCoords = base + ivec3(dx, dy, dz);
                int pIdx = DDGIGetProbeIndex(pCoords, probeCounts);
                probeStates[pIdx].isRelevant = true;
            }
        }
    }
}