#version 460

#include "../../common/constants.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/post_processing.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D u_outputImage;

#if defined(RE_ENABLED)
layout (binding = 1) uniform sampler2D BaseColorMetallic;
layout (binding = 2) uniform sampler2D NormalXYRoughnessMisc;
layout (binding = 3) uniform sampler2D VelocityXYOcclusionSubSurface;
layout (binding = 9) uniform usampler2D VisibilityTexture;
#else
layout (binding = 1) uniform sampler2D BaseColorMetallic;
layout (binding = 2) uniform sampler2D NormalXYRoughnessMisc;
layout (binding = 3) uniform sampler2D VelocityXYOcclusionSubSurface;
layout (binding = 6) uniform sampler2D GBufferWorldMirrorMaskTexture;
layout (binding = 7) uniform sampler2D GBufferEmissiveTexture;
#endif

layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;

layout (binding = 10) uniform usampler2D u_oceanFlagsTexture;
layout (binding = 11) uniform sampler2D u_depthTexture;
layout (binding = 12) uniform sampler2D u_emissiveTexture;

readonly restrict layout(std430, binding = 2) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = 3) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };

#define NONE 0
#define BASE_COLOR 1
#define NORMALS 2
#define RMA 3
#define ROUGHNESS 4
#define METALLIC 5
#define AO 6
#define CAMERA_NDOTL 7
#define TILE_HEATMAP_LIGHTS 8,
#define TILE_HEATMAP_BLOOD_DECALS 9
#define TILE_HEATMAP_CHRISTMAS_LIGHTS 10
#define INDIRECT_DIFFUSE 11
#define VELOCITY 12
#define VIS_BUFFER 13
#define DEPTH 14
#define WORLD_POSITION 15
#define EMISSIVE 16

vec3 IntegerToColor(uint x) {
    x = ((x >> 16) ^ x) * 0x45d9f3bE;
    x = ((x >> 16) ^ x) * 0x45d9f3bE;
    x = (x >> 16) ^ x;
    return vec3(float(x & 0xFFu) / 255.0, float((x >> 8) & 0xFFu) / 255.0, float((x >> 16) & 0xFFu) / 255.0);
}

vec3 GetBaseColor(ivec2 px) {
    //#if defined(RE_ENABLED)
        return texelFetch(BaseColorMetallic, px, 0).rgb;
    //#else
    //    return texelFetch(GBufferBaseColorTexture, px, 0).rgb;
    //#endif
}

vec3 GetNormal(ivec2 px) {
    //#if defined(RE_ENABLED)
        vec4 normalXYRoughnessMisc = texelFetch(NormalXYRoughnessMisc, px, 0);
        return DecodeNormal(normalXYRoughnessMisc.rg);
    //#else
    //    return texelFetch(GBufferNormalTexture, px, 0).rgb;
    //#endif
}

vec3 GetRoughness(ivec2 px) {
    //#if defined(RE_ENABLED)
        return vec3(texelFetch(NormalXYRoughnessMisc, px, 0).b);
    //#else
    //    return vec3(texelFetch(GBufferRMATexture, px, 0).r);
    //#endif
}

vec3 GetMetallic(ivec2 px) {
    //#if defined(RE_ENABLED)
        return vec3(texelFetch(BaseColorMetallic, px, 0).a);
    //#else
    //    return vec3(texelFetch(GBufferRMATexture, px, 0).g);
    //#endif
}

vec3 GetAO(ivec2 px) {
    //#if defined(RE_ENABLED)
        return vec3(texelFetch(VelocityXYOcclusionSubSurface, px, 0).b);
    //#else
    //    return vec3(texelFetch(GBufferRMATexture, px, 0).b);
    //#endif
}

vec3 GetRMA(ivec2 px) {
    //#if defined(RE_ENABLED)
        return vec3(GetRoughness(px).r, GetMetallic(px).r, GetAO(px).r);
    //#else
    //    return texelFetch(GBufferRMATexture, px, 0).rgb;
    //#endif
}

vec3 GetCameraNdotL(ivec2 px) {
    ivec2 outputImageSize = imageSize(u_outputImage);
    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportDataArr[viewportIndex]);

    ViewportData viewportData = viewportDataArr[viewportIndex];
    mat4 inverseView = viewportData.inverseView;

    vec3 normal = GetNormal(px);
    vec3 lightDir = normalize(inverseView[2].xyz);
    float ndotl = max(dot(normal.xyz, lightDir), 0.0);

    return GetBaseColor(px) * ndotl;
    //return vec3(ndotl);
}

vec3 GetIndirectDiffuse(ivec2 px) {
    ivec2 outputImageSize = imageSize(u_outputImage);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec3 indirectDiffuseTexture =  texture(IndirectDiffuseTexture, screenUV).rgb;
    vec3 result = Tonemap_ACES(indirectDiffuseTexture);
    result = pow(result, vec3(1.0 / 2.2));
    result = clamp(result, 0, 1);
    result = mix(result, Tonemap_ACES(result), 0.125);
    return (result);
}

vec3 GetVelocity(ivec2 px) {
    vec2 velocity = vec2(0);
    //#if defined(RE_ENABLED)
        velocity = texelFetch(VelocityXYOcclusionSubSurface, px, 0).rg;
    //#else
    //    velocity = texelFetch(VelocityOcclusionSubSurface, px, 0).rg;
    //#endif
    float gain = 20.0;
    return vec3(velocity * gain + 0.5, 0.5);
}

vec3 GetVisBuffer(ivec2 px) {
    #if defined(RE_ENABLED)
    uvec2 visibilityData = texelFetch(VisibilityTexture, px, 0).rg;
    #else
    uvec2 visibilityData = uvec2(0, 0);
    #endif

    uint meshID = visibilityData.x;
    uint primitiveID = visibilityData.y;

    // Check if background pixel
    if (meshID == 0 && primitiveID == 0) {
        return vec3(0.05, 0.05, 0.05);
    }

    // Generate distinctive color configurations
    vec3 meshColor = IntegerToColor(meshID);
    vec3 primColor = IntegerToColor(primitiveID);

    // Combine paths to highlight distinct meshes while showing individual triangles
    return mix(meshColor, primColor, 0.2);
}

vec3 GetVisBufferUVs(ivec2 px) {
    #if defined(RE_ENABLED)
    uvec2 visibilityData = texelFetch(VisibilityTexture, px, 0).rg;

    #else
    return vec3(0, 0, 0);
    #endif

    return vec3(0, 0, 0);
}

vec3 GetDepth(ivec2 px) {
    float depth = texelFetch(u_depthTexture, px, 0).r;
    return vec3(depth, 0, 0);
}

vec3 GetWorldPosition(ivec2 px) {
    ivec2 outputImageSize = imageSize(u_outputImage);
    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportDataArr[viewportIndex]);

    ViewportData viewportData = viewportDataArr[viewportIndex];
    mat4 inverseProjectionViewReverseZ = viewportData.inverseProjectionViewReverseZ;

    float depth = texelFetch(u_depthTexture, px, 0).r;
    return ReconstructWorldPos(viewportUV, depth, inverseProjectionViewReverseZ);
}

vec3 GetEmissive(ivec2 px) {
    return texelFetch(u_emissiveTexture, px, 0).rgb;
}

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(u_outputImage);
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;

    vec3 finalColor = vec3(0, 0, 0);

    if (rendererData.rendererOverrideState == BASE_COLOR)       finalColor = GetBaseColor(px);
    if (rendererData.rendererOverrideState == NORMALS)          finalColor = GetNormal(px);
    if (rendererData.rendererOverrideState == RMA)              finalColor = GetRMA(px);
    if (rendererData.rendererOverrideState == ROUGHNESS)        finalColor = GetRoughness(px);
    if (rendererData.rendererOverrideState == METALLIC)         finalColor = GetMetallic(px);
    if (rendererData.rendererOverrideState == AO)               finalColor = GetAO(px);
    if (rendererData.rendererOverrideState == CAMERA_NDOTL)     finalColor = GetCameraNdotL(px);
    if (rendererData.rendererOverrideState == INDIRECT_DIFFUSE) finalColor = GetIndirectDiffuse(px);
    if (rendererData.rendererOverrideState == VELOCITY)         finalColor = GetVelocity(px);
    if (rendererData.rendererOverrideState == VIS_BUFFER)       finalColor = GetVisBuffer(px);
    if (rendererData.rendererOverrideState == DEPTH)            finalColor = GetDepth(px);
    if (rendererData.rendererOverrideState == WORLD_POSITION)   finalColor = GetWorldPosition(px);
    if (rendererData.rendererOverrideState == EMISSIVE)         finalColor = GetEmissive(px);

    imageStore(u_outputImage, px, vec4(finalColor, 1));


    //vec3 test = texelFetch(VelocityXYOcclusionSubSurface, px, 0).rgb;
    //imageStore(u_outputImage, px, vec4(test, 1));

}
