#version 460

#include "../../common/constants.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/post_processing.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D u_outputImage;

#if defined(MSAA_ENABLED)
layout (binding = 1) uniform sampler2DMS MSAABaseColorTexture;
layout (binding = 2) uniform sampler2DMS MSAANormalTexture;
layout (binding = 3) uniform sampler2DMS MSAAMaterialTexture;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
#elif defined(RE_ENABLED)
layout (binding = 1) uniform sampler2D BaseColorMetallic;
layout (binding = 2) uniform sampler2D NormalXYRoughnessMisc;
layout (binding = 3) uniform sampler2D VelocityXYOcclusionSubSurface;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
layout (binding = 9) uniform usampler2D VisibilityTexture;
#else
layout (binding = 1) uniform sampler2D GBufferBaseColorTexture;
layout (binding = 2) uniform sampler2D GBufferNormalTexture;
layout (binding = 3) uniform sampler2D GBufferRMATexture;
layout (binding = 4) uniform sampler2D VelocityOcclusionSubSurface;
layout (binding = 6) uniform sampler2D GBufferWorldMirrorMaskTexture;
layout (binding = 7) uniform sampler2D GBufferEmissiveTexture;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
#endif

layout (binding = 9) uniform usampler2D u_oceanFlagsTexture;

shared vec3 sharedDebugOutputColor;

readonly restrict layout(std430, binding = 1) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer { ViewportData viewportDataArr[]; };

uniform bool u_heightMapEditor;
uniform float u_brushSize;

vec3 IntegerToColor(uint x) {
    x = ((x >> 16) ^ x) * 0x45d9f3bE;
    x = ((x >> 16) ^ x) * 0x45d9f3bE;
    x = (x >> 16) ^ x;
    return vec3(float(x & 0xFFu) / 255.0, float((x >> 8) & 0xFFu) / 255.0, float((x >> 16) & 0xFFu) / 255.0);
}

vec3 GetVisiblity() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);

#if defined(MSAA_ENABLED)
    uvec2 visibilityData = uvec2(0, 0);
#elif defined(RE_ENABLED)
    uvec2 visibilityData = texelFetch(VisibilityTexture, px, 0).rg;
#else
    uvec2 visibilityData = uvec2(0, 0);
#endif

    uint meshID = visibilityData.x;
    uint primitiveID = visibilityData.y;

    // Check if background pixel
    if (meshID == 0 && primitiveID == 0) {
        return vec3(0.05, 0.05, 0.05);
    }

    // Generate distinctive color configurations
    vec3 meshColor = IntegerToColor(meshID);
    vec3 primColor = IntegerToColor(primitiveID);

    // Combine paths to highlight distinct meshes while showing individual triangles
    return mix(meshColor, primColor, 0.2);
}

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 u_outputImageSize = imageSize(u_outputImage);

    // Don't process out of bounds pixels
    if (px.x >= u_outputImageSize.x || px.y >= u_outputImageSize.y) return;

    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, u_outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(u_outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportDataArr[viewportIndex]);

    ViewportData viewportData = viewportDataArr[viewportIndex];
    mat4 viewMatrix = viewportData.view;
    mat4 inverseView = viewportData.inverseView;

#if defined(MSAA_ENABLED)
    ivec2 pxMS = ivec2(screenUV * vec2(textureSize(MSAAMaterialTexture)));
	vec3 lightingColor = imageLoad(u_outputImage, px).rgb;
    vec3 baseColor = texelFetch(MSAABaseColorTexture, px, 0).rgb;
    vec3 rma = texelFetch(MSAAMaterialTexture, pxMS, 0).rgb;
    vec3 emissive = vec3(0);
    float mirrorMask = 0.0;
    vec3 rawNormal = texelFetch(MSAANormalTexture, px, 0).rgb;
    vec3 normal = normalize(rawNormal * 2.0 - 1.0);
    vec2 velocity = vec2(0, 0);

#elif defined(RE_ENABLED)
    vec4 normalXYRoughnessMisc = texture(NormalXYRoughnessMisc, screenUV);
    vec3 normal = DecodeNormal(normalXYRoughnessMisc.rg);
    float roughness = normalXYRoughnessMisc.b;
    float misc = normalXYRoughnessMisc.a;

    vec4 baseColorMetallic = texture(BaseColorMetallic, screenUV);
    vec3 baseColor = baseColorMetallic.rgb;
    float metallic = baseColorMetallic.a;

    vec4 velocityXYOcclusionSubSurface = texture(VelocityXYOcclusionSubSurface, screenUV).rgba;
    float ao =velocityXYOcclusionSubSurface.b;
    float subSurface = velocityXYOcclusionSubSurface.a;

    vec2 velocity = velocityXYOcclusionSubSurface.rg;
    vec3 rma = vec3(roughness, metallic, ao);

    // Random non GBuffer stuff
	vec3 lightingColor = imageLoad(u_outputImage, px).rgb;

#else
	vec3 lightingColor = imageLoad(u_outputImage, px).rgb;
    vec3 baseColor = texture(GBufferBaseColorTexture, screenUV).rgb;
    vec3 normal = texture(GBufferNormalTexture, screenUV).rgb;
    vec3 rma = texture(GBufferRMATexture, screenUV).rgb;
    vec3 emissive = texture(GBufferEmissiveTexture, screenUV).rgb;
    float mirrorMask = texture(GBufferWorldMirrorMaskTexture, screenUV).r;
    vec2 velocity = texture(VelocityOcclusionSubSurface, screenUV).rg;

#endif

    vec3 indirectDiffuseTexture =  texture(IndirectDiffuseTexture, screenUV).rgb;

    vec3 finalColor = lightingColor.rgb * vec3(1,0,0);

    // Renderer override states
    if (rendererData.rendererOverrideState == 1) {
        finalColor = baseColor;
    }
    else if (rendererData.rendererOverrideState == 2) {
        finalColor = normal;
    }
    else if (rendererData.rendererOverrideState == 3) {
        finalColor = rma;
    }
    else if (rendererData.rendererOverrideState == 4) {
        finalColor = vec3(rma.r);
    }
    else if (rendererData.rendererOverrideState == 5) {
        finalColor =  vec3(rma.g);
    }
    else if (rendererData.rendererOverrideState == 6) {
        finalColor = vec3(rma.b);
    }
    else if (rendererData.rendererOverrideState == 7) {
        return; // for map editor

        vec3 lightDir = normalize(inverseView[2].xyz);
        float ndotl = max(dot(normal.xyz, lightDir), 0.0);
        vec3 lightColor = vec3(0.5, 0.5, 0.6) * ndotl;
        vec3 color = baseColor.rgb * ndotl;
        finalColor = mix(baseColor.rgb, color, 0.5);
    }

    else if (rendererData.rendererOverrideState == 11) {
        //finalColor = indirectDiffuseTexture * 1.5;
        finalColor = Tonemap_ACES(indirectDiffuseTexture);
        finalColor = pow(finalColor, vec3(1.0 / 2.2));
        finalColor = clamp(finalColor, 0, 1);
        finalColor = mix(finalColor, Tonemap_ACES(finalColor), 0.125);

        //uint flag = texelFetch(u_oceanFlagsTexture, px, 0).r;
        //
        //if      (flag == 0) finalColor = vec3(0, 0, 0);
        //else if (flag == 1) finalColor = vec3(1, 0, 0);
        //else if (flag == 2) finalColor = vec3(0, 1, 0);
        //else if (flag == 3) finalColor = vec3(0, 0, 1);
        //else if (flag == 4) finalColor = vec3(0, 1, 1);
    }

    // Velocity
    else if (rendererData.rendererOverrideState == 12) {
        float gain = 20.0;
        finalColor = vec3(velocity * gain + 0.5, 0.5);

    }
    // Visiblity
    else if (rendererData.rendererOverrideState == 13) {
        finalColor = GetVisiblity();
    }

    // Below did work, but you commented it out when implementing MSAA coz u have no world pos texture for MSAA. Reconstruct pos from depth!

    // Height map paint dot
    //if (u_heightMapEditor) {
    //    vec2 mouseUV = vec2(rendererData.normalizedMouseX, 1 - rendererData.normalizedMouseY);
    //    vec3 mouseWorldPos = texture(GBufferWorldPositionexture, mouseUV).rgb;
    //
    //    // If there is no normal, we have no valid sample, aka skybox
    //    if (normal != vec3(0,0,0)) {
    //        vec3 fragWorldPos = texture(GBufferWorldPositionexture, screenUV).rgb;
    //        float brushSize = u_brushSize;
    //        float worldDist = length(fragWorldPos.xz - mouseWorldPos.xz);
    //        float pixelDist = worldDist / HEIGHTMAP_SCALE_XZ;
    //        float falloff = smoothstep(0.0, u_brushSize, pixelDist);
    //        vec3 dotColor = mix(finalColor, vec3(0.0, 0.5, 1.0), 1.0 - falloff);
    //        finalColor = mix(finalColor, dotColor, 0.75);
    //    }
    //}

    imageStore(u_outputImage, px, vec4(finalColor, 1));
}
