#version 460

#include "../../common/constants.glsl"
#include "../../common/normal_encoding.glsl"
#include "../../common/types.glsl"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D OutputImage;

#if defined(MSAA_ENABLED)
layout (binding = 1) uniform sampler2DMS MSAABaseColorTexture;
layout (binding = 2) uniform sampler2DMS MSAANormalTexture;
layout (binding = 3) uniform sampler2DMS MSAAMaterialTexture;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
#elif defined(RE_ENABLED)
layout (binding = 1) uniform sampler2D BaseColorMetallic;
layout (binding = 2) uniform sampler2D NormalXYRoughnessMisc;
layout (binding = 3) uniform sampler2D VelocityXYOcclusionSubSurface;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
#else
layout (binding = 1) uniform sampler2D GBufferBaseColorTexture;
layout (binding = 2) uniform sampler2D GBufferNormalTexture;
layout (binding = 3) uniform sampler2D GBufferRMATexture;
layout (binding = 4) uniform sampler2D VelocityOcclusionSubSurface;
layout (binding = 5) uniform usampler2D ViewportIndexTexture;
layout (binding = 6) uniform sampler2D GBufferWorldMirrorMaskTexture;
layout (binding = 7) uniform sampler2D GBufferEmissiveTexture;
layout (binding = 8) uniform sampler2D IndirectDiffuseTexture;
#endif

shared vec3 sharedDebugOutputColor;

readonly restrict layout(std430, binding = 1) buffer rendererDataBuffer { RendererData rendererData; };
readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer { ViewportData viewportData[]; };

uniform bool u_heightMapEditor;
uniform float u_brushSize;

void main() {
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(OutputImage);
    vec2 uv_screenspace = (vec2(pixelCoords) + 0.5) / vec2(outputImageSize);

    // Don't process out of bounds pixels
    if (pixelCoords.x >= outputImageSize.x || pixelCoords.y >= outputImageSize.y) {
        return;
    }

#if defined(MSAA_ENABLED)
    ivec2 pixelCoordsMS = ivec2(uv_screenspace * vec2(textureSize(MSAAMaterialTexture)));
	vec3 lightingColor = imageLoad(OutputImage, pixelCoords).rgb;
    vec3 baseColor = texelFetch(MSAABaseColorTexture, pixelCoords, 0).rgb;
    vec3 rma = texelFetch(MSAAMaterialTexture, pixelCoordsMS, 0).rgb;
    vec3 emissive = vec3(0);
    float mirrorMask = 0.0;
    uint viewportIndex = 0; // TODO!!!!!!!!!! Reconstruct from screen coords
    vec3 rawNormal = texelFetch(MSAANormalTexture, pixelCoords, 0).rgb;
    vec3 normal = normalize(rawNormal * 2.0 - 1.0);
    vec2 velocity = vec2(0, 0);

#elif defined(RE_ENABLED)
    vec4 normalXYRoughnessMisc = texture(NormalXYRoughnessMisc, uv_screenspace);
    vec3 normal = DecodeNormal(normalXYRoughnessMisc.rg);
    float roughness = normalXYRoughnessMisc.b;
    float misc = normalXYRoughnessMisc.a;

    vec4 baseColorMetallic = texture(BaseColorMetallic, uv_screenspace);
    vec3 baseColor = baseColorMetallic.rgb;
    float metallic = baseColorMetallic.a;

    vec4 velocityXYOcclusionSubSurface = texture(VelocityXYOcclusionSubSurface, uv_screenspace).rgba;
    float ao =velocityXYOcclusionSubSurface.b;
    float subSurface = velocityXYOcclusionSubSurface.a;

    vec2 velocity = velocityXYOcclusionSubSurface.rg;
    vec3 rma = vec3(roughness, metallic, ao);

    // Random non GBuffer stuff
	vec3 lightingColor = imageLoad(OutputImage, pixelCoords).rgb;
    uint viewportIndex = 0;

#else
	vec3 lightingColor = imageLoad(OutputImage, pixelCoords).rgb;
    vec3 baseColor = texture(GBufferBaseColorTexture, uv_screenspace).rgb;
    vec3 normal = texture(GBufferNormalTexture, uv_screenspace).rgb;
    vec3 rma = texture(GBufferRMATexture, uv_screenspace).rgb;
    vec3 emissive = texture(GBufferEmissiveTexture, uv_screenspace).rgb;
    float mirrorMask = texture(GBufferWorldMirrorMaskTexture, uv_screenspace).r;
    uint viewportIndex = texture(ViewportIndexTexture, uv_screenspace).r;
    vec2 velocity = texture(VelocityOcclusionSubSurface, uv_screenspace).rg;

#endif

    vec3 indirectDiffuseTexture =  texture(IndirectDiffuseTexture, uv_screenspace).rgb;

    mat4 viewMatrix = viewportData[viewportIndex].view;
    mat4 inverseView = viewportData[viewportIndex].inverseView;

    vec3 finalColor = lightingColor.rgb * vec3(1,0,0);

    // Renderer override states
    if (rendererData.rendererOverrideState == 1) {
        finalColor = baseColor;
    }
    else if (rendererData.rendererOverrideState == 2) {
        finalColor = normal;
    }
    else if (rendererData.rendererOverrideState == 3) {
        finalColor = rma;
    }
    else if (rendererData.rendererOverrideState == 4) {
        finalColor = vec3(rma.r);
    }
    else if (rendererData.rendererOverrideState == 5) {
        finalColor =  vec3(rma.g);
    }
    else if (rendererData.rendererOverrideState == 6) {
        finalColor = vec3(rma.b);
    }
    else if (rendererData.rendererOverrideState == 7) {
        return; // for map editor

        vec3 lightDir = normalize(inverseView[2].xyz);
        float ndotl = max(dot(normal.xyz, lightDir), 0.0);
        vec3 lightColor = vec3(0.5, 0.5, 0.6) * ndotl;
        vec3 color = baseColor.rgb * ndotl;
        finalColor = mix(baseColor.rgb, color, 0.5);
    }

    else if (rendererData.rendererOverrideState == 11) {
        finalColor = indirectDiffuseTexture;// * 1.5;
    }

    // Velocity
    else if (rendererData.rendererOverrideState == 12) {
        float gain = 20.0;
        finalColor = vec3(velocity * gain + 0.5, 0.5);
    }

    // Below did work, but you commented it out when implementing MSAA coz u have no world pos texture for MSAA. Reconstruct pos from depth!

    // Height map paint dot
    //if (u_heightMapEditor) {
    //    vec2 mouseUV = vec2(rendererData.normalizedMouseX, 1 - rendererData.normalizedMouseY);
    //    vec3 mouseWorldPos = texture(GBufferWorldPositionexture, mouseUV).rgb;
    //
    //    // If there is no normal, we have no valid sample, aka skybox
    //    if (normal != vec3(0,0,0)) {
    //        vec3 fragWorldPos = texture(GBufferWorldPositionexture, uv_screenspace).rgb;
    //        float brushSize = u_brushSize;
    //        float worldDist = length(fragWorldPos.xz - mouseWorldPos.xz);
    //        float pixelDist = worldDist / HEIGHTMAP_SCALE_XZ;
    //        float falloff = smoothstep(0.0, u_brushSize, pixelDist);
    //        vec3 dotColor = mix(finalColor, vec3(0.0, 0.5, 1.0), 1.0 - falloff);
    //        finalColor = mix(finalColor, dotColor, 0.75);
    //    }
    //}

    imageStore(OutputImage, pixelCoords, vec4(finalColor, 1));
}
