#define DESC_IDX_SAMPLERS 0
#define DESC_IDX_TEXTURES 1
#define DESC_IDX_UBOS 2
#define DESC_IDX_SSBOS 3
#define DESC_IDX_STORAGE_IMAGES_RGBA32F 4
#define DESC_IDX_STORAGE_IMAGES_RGBA16F 5
#define DESC_IDX_STORAGE_IMAGES_RGBA8 6
#define DESC_IDX_UINT_TEXTURES 7
#define DESC_IDX_TEXTURE_SAMPLERS 8

#define VULKAN_SAMPLER_IDX_LINEAR 0
#define VULKAN_SAMPLER_IDX_NEAREST 1

#define VULKAN_TEXTURE_IDX_PRESENT 9000
#define VULKAN_TEXTURE_IDX_GBUFFER_DEPTH 9001

#define VULKAN_UINT_TEXTURE_IDX_GBUFFER_VISIBILITY 0

#define VULKAN_STORAGE_IMAGE_IDX_GBUFFER_LIGHTING 0
