#pragma once

#define DESC_IDX_SAMPLERS 0
#define DESC_IDX_TEXTURES 1
#define DESC_IDX_UBOS 2
#define DESC_IDX_SSBOS 3
#define DESC_IDX_STORAGE_IMAGES_RGBA32F 4
#define DESC_IDX_STORAGE_IMAGES_RGBA16F 5
#define DESC_IDX_STORAGE_IMAGES_RGBA8 6
