#version 430 core
#include "../../common/constants.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (rgba16f, binding = 0) uniform image2D LightingImage;
layout (r8ui, binding = 1) readonly uniform uimage2D u_oceanFlagsImage;
layout (binding = 2) uniform sampler2D GaussianFinalLighting;
layout (binding = 3) uniform sampler2D WaterColorTexture;
layout (binding = 4) uniform sampler2D WaterDUDVTexture;

readonly restrict layout(std430, binding = 1) buffer rendererDataBuffer { RendererData  rendererData; };
readonly restrict layout(std430, binding = 2) buffer viewportDataBuffer { ViewportData  viewportDataArr[] ; };

uniform float u_time;
uniform vec2 u_resolution;

vec3 GetWorldRay(vec2 fragCoord, vec2 resolution, mat4 inverseProjectionView, vec3 viewPos) {
    vec2 ndc = (fragCoord / resolution) * 2.0 - 1.0;
    vec4 clip = vec4(ndc, 1.0, 1.0);
    vec4 world = inverseProjectionView * clip;
    world /= world.w;
    return normalize(world.xyz - viewPos);
}

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(LightingImage);

    // Bail if outta bounds
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;
    
    uint flag = imageLoad(u_oceanFlagsImage, px).r;
    
    // Early out if pixel is the water surface or geometry above water surface
    if (flag == 0u || flag == 1u) return;

    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    ViewportData viewportData = viewportDataArr[viewportIndex];

    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);
    vec2 viewportUV = ScreenUVToViewportUV(screenUV, viewportData);

    // Sample ocean lighting texture
    vec3 waterColor = texelFetch(WaterColorTexture, px, 0).rgb;

    // Get world ray
    mat4 inverseProjectionView = viewportData.inverseProjectionViewReverseZ;
    vec3 viewPos = viewportData.viewPos.xyz;
    vec2 viewportOrigin = vec2(viewportData.xOffset, viewportData.yOffset);
    vec2 viewportSize = vec2(viewportData.width, viewportData.height);
    vec3 rayDir = GetWorldRay(px, inverseProjectionView, viewPos, viewportOrigin, viewportSize);

    // calculate depth-based world ray fog
    vec3 down = vec3(0.0, -1.0, 0.0);
    float downwardness = clamp(dot(rayDir, down), 0.0, 1.0);
    float darknessCurve = 0.95;
    float darkness = mix(1.0, 0.0, pow(downwardness, darknessCurve));
    vec3 finalRayFog = vec3(0.4, 0.8, 0.6) * darkness * 0.00125;

    // calculate refraction distortion mapping
    const float distortionSpeed = 0.075;
    const float distortionFactor = 0.0024;
    float offsetX = fract(u_time * distortionSpeed);
    vec2 uv_dudv = screenUV + vec2(offsetX, 0.0);
    vec2 distortion = texture(WaterDUDVTexture, uv_dudv).rg * 2.0 - 1.0;

    vec2 uv_refraction = screenUV + (distortion * distortionFactor);
    uv_refraction = clamp(uv_refraction, vec2(0.0), vec2(1.0));

    vec3 refactoredFinalLighting = texture(GaussianFinalLighting, uv_refraction).rgb;

    // blend water tint into refracted lighting
    vec3 depthTint = refactoredFinalLighting * UNDER_WATER_TINT * 1.5;
    refactoredFinalLighting = mix(depthTint, refactoredFinalLighting, 0.5);

    // pixelUnderwater && oceanGeometry
    if (flag == 2u) {
        vec3 color = refactoredFinalLighting.rgb + (waterColor * waterColor * 5.75) + (waterColor * 0.25);
        color = mix(color, color * UNDER_WATER_TINT * UNDER_WATER_TINT, 0.25);

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
    else {
        // output final underwater color blend
        vec3 color = refactoredFinalLighting.rgb;
        color = mix(color, color * UNDER_WATER_TINT * UNDER_WATER_TINT, 0.99);
        color -= finalRayFog;
        color *= 0.5;

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
}