#version 430 core
#include "../../common/OpenGL/GL_binding_indices.glsl"
#include "../../common/constants.glsl"
#include "../../common/types.glsl"
#include "../../common/util.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (rgba16f, binding = 0) uniform image2D LightingImage;
layout (r8ui, binding = 1) readonly uniform uimage2D u_oceanFlagsImage;
layout (binding = 2) uniform sampler2D GaussianFinalLighting;
layout (binding = 3) uniform sampler2D WaterColorTexture;
layout (binding = 4) uniform sampler2D WaterDUDVTexture;

readonly restrict layout(std430, binding = SSBO_IDX_RENDERER_DATA) buffer rendererDataBuffer { RendererData  rendererData; };
readonly restrict layout(std430, binding = SSBO_IDX_VIEWPORT_DATA) buffer viewportDataBuffer { ViewportData  viewportDataArr[] ; };

uniform float u_time;

struct OceanUnderwaterCompositeSettings {
    vec3 underwaterTint;
    vec3 rayFogColor;
    float rayFogStrength;
    float darknessCurve;
    float distortionSpeed;
    float distortionStrength;
    float depthTintStrength;
    float depthTintOriginalWeight;
    float geometryWaterColorSquaredStrength;
    float geometryWaterColorStrength;
    float geometryTintStrength;
    float openWaterTintStrength;
    float openWaterBrightness;
};

uniform OceanUnderwaterCompositeSettings u_composite;

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outputImageSize = imageSize(LightingImage);

    // Bail if outta bounds
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;
    
    uint flag = imageLoad(u_oceanFlagsImage, px).r;
    
    // Early out if pixel is the water surface or geometry above water surface
    if (flag == 0u || flag == 1u) return;

    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    ViewportData viewportData = viewportDataArr[viewportIndex];

    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);

    // Sample ocean lighting texture
    vec3 waterColor = texelFetch(WaterColorTexture, px, 0).rgb;

    // Get world ray
    mat4 inverseProjectionView = viewportData.inverseJitteredProjectionViewReverseZ;
    vec3 viewPos = viewportData.viewPos.xyz;
    vec2 viewportOrigin = vec2(viewportData.xOffset, viewportData.yOffset);
    vec2 viewportSize = vec2(viewportData.width, viewportData.height);
    vec3 rayDir = GetWorldRay_GL(px, inverseProjectionView, viewPos, viewportOrigin, viewportSize);

    // calculate depth-based world ray fog
    vec3 down = vec3(0.0, -1.0, 0.0);
    float downwardness = clamp(dot(rayDir, down), 0.0, 1.0);
    float darkness = mix(1.0, 0.0, pow(downwardness, u_composite.darknessCurve));
    vec3 finalRayFog = u_composite.rayFogColor * darkness * u_composite.rayFogStrength;

    // calculate refraction distortion mapping
    float offsetX = fract(u_time * u_composite.distortionSpeed);
    vec2 uv_dudv = screenUV + vec2(offsetX, 0.0);
    vec2 distortion = texture(WaterDUDVTexture, uv_dudv).rg * 2.0 - 1.0;

    vec2 uv_refraction = screenUV + (distortion * u_composite.distortionStrength);
    uv_refraction = clamp(uv_refraction, vec2(0.0), vec2(1.0));

    vec3 refactoredFinalLighting = texture(GaussianFinalLighting, uv_refraction).rgb;

    // blend water tint into refracted lighting
    vec3 depthTint = refactoredFinalLighting * u_composite.underwaterTint * u_composite.depthTintStrength;
    refactoredFinalLighting = mix(depthTint, refactoredFinalLighting, u_composite.depthTintOriginalWeight);

    // pixelUnderwater && oceanGeometry
    if (flag == 2u) {
        vec3 color = refactoredFinalLighting.rgb + (waterColor * waterColor * u_composite.geometryWaterColorSquaredStrength) + (waterColor * u_composite.geometryWaterColorStrength);
        color = mix(color, color * u_composite.underwaterTint * u_composite.underwaterTint, u_composite.geometryTintStrength);

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
    else {
        // output final underwater color blend
        vec3 color = refactoredFinalLighting.rgb;
        color = mix(color, color * u_composite.underwaterTint * u_composite.underwaterTint, u_composite.openWaterTintStrength);
        color -= finalRayFog;
        color *= u_composite.openWaterBrightness;

        imageStore(LightingImage, px, vec4(color, 1.0));
    }
}
