#version 430
#include "../../common/constants.glsl"
#include "../../common/util.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (rgba16f, binding = 0) uniform image2D LightingImage; // output
layout (r8ui, binding = 1) readonly uniform uimage2D u_oceanMaskImage;
layout (binding = 2) uniform sampler2D WaterColorTexture;
layout (binding = 3) uniform sampler2D waterDUDVTexture;
layout (binding = 4) uniform sampler2D DownSampledFinalLightingTexture;

layout(std430, binding = 1) readonly restrict buffer rendererDataBuffer { RendererData rendererData; };
layout(std430, binding = 2) readonly restrict buffer viewportDataBuffer { ViewportData viewportDataArr[]; };

uniform float u_time;
uniform float u_oceanYOrigin;
uniform vec2 u_resolution;

const float distortionSpeed = 0.05;
const float distortionFactor = 0.004;
const float waterUVScaling = 0.15;

vec3 IntersectRayWithGroundPlane(vec3 rayOrigin, vec3 rayDir, float groundHeight) {
    const float epsilon = 1e-5;
    float denom = rayDir.y + sign(rayDir.y) * epsilon;
    float t = (groundHeight - rayOrigin.y) / denom;
    return rayOrigin + rayDir * t;
}

void main() {
	ivec2 px = ivec2(gl_GlobalInvocationID.xy);   
    ivec2 outputImageSize = imageSize(LightingImage);

    // Don't process out of bounds pixels
    if (px.x >= outputImageSize.x || px.y >= outputImageSize.y) return;
    
    // Early out if the pixel is not the ocean surface
    uint oceanMask = imageLoad(u_oceanMaskImage, px).r;
    if (oceanMask != 1u) return;
    
    uint viewportIndex = ComputeViewportIndexFromSplitscreenMode(px, outputImageSize, rendererData.splitscreenMode);
    vec2 screenUV = (vec2(px) + 0.5) / vec2(outputImageSize);

    
    vec4 lighting = imageLoad(LightingImage, px);
    vec3 waterColor = texelFetch(WaterColorTexture, px, 0).rgb;

    // Get world ray
    ViewportData viewportData = viewportDataArr[viewportIndex];
    mat4 inverseProjectionView = viewportData.inverseProjectionViewReverseZ;
    vec3 viewPos = viewportData.viewPos.xyz;
    vec2 viewportOrigin = vec2(viewportData.xOffset, viewportData.yOffset);
    vec2 viewportSize = vec2(viewportData.width, viewportData.height);
    vec3 rayDir = GetWorldRay(px, inverseProjectionView, viewPos, viewportOrigin, viewportSize);

    // Cast ray at water plane
    vec3 rayOrigin = viewPos;
    float planeHeight = u_oceanYOrigin + 100;
    float t = (planeHeight - rayOrigin.y) / rayDir.y; // distance to ray hit
    
    vec3 waterWorldPos = rayOrigin + rayDir * t;
    vec2 uv_waterSurface = vec2(waterWorldPos.x, waterWorldPos.z) * waterUVScaling;
    float offsetX = mod(u_time * distortionSpeed, 1.0);
    vec2 uv_dudv = vec2(uv_waterSurface + vec2(offsetX, 0));
    vec2 distortion = texture(waterDUDVTexture, uv_dudv).rg * 2 - 1;
    vec2 uv_refraction = screenUV + (distortion * distortionFactor);
    uv_refraction = clamp(uv_refraction, 0, 1);
 
    vec3 refractedColor = texture(DownSampledFinalLightingTexture, uv_refraction).rgb;
    vec3 finalColor = (refractedColor * UNDER_WATER_TINT * 0.2) + waterColor;

    imageStore(LightingImage, px, vec4(vec3(finalColor), 1.0));
}